#!/usr/bin/env python3

import sys

def run():
    if len(sys.argv) not in (2, 3):
        print('Usage: sudoku_adder <sum> [length]')
        sys.exit()

    solutions = []
    find_terms(solutions, int(sys.argv[1]))

    if len(sys.argv) == 3:
        solutions = [i for i in solutions if len(i) == int(sys.argv[2])]

    if len(solutions) == 0:
        print("No solutions found")

    for soln in solutions:
        print(soln)

def find_terms(solutions, num, *digits):
    used_digits = unpack(digits)

    if num == 0:
        if sorted(used_digits) not in solutions:
            solutions.append(sorted(used_digits))
    elif num < 0:
        return

    for i in filter(lambda item: item not in used_digits, range(1,10)):
        find_terms(solutions, num - i, used_digits, i)

def unpack(tup):
    if len(tup) <= 1:
        return tup

    res = []

    if len(tup[0]) > 0:
        res = [x for x in tup[0]]

    return tuple(res + [tup[1]])

if __name__ == '__main__':
    run()
